### ISSUE TITLE
Multiple instances of taggd

### ISSUE THREAD

**Issue by rafalolszewskii** [timseverien/taggd#55]
Whenever I'm doing

```js
const tagImage1 = document.getElementById('userProfile');
const tagImage2 = document.getElementById('peopleView');

const taggd1 = new Taggd(tagImage1, options, tags);
const taggd2 = new Taggd(tagImage2, options, tags);
```
(`tags` and `options` stays the same)
It only creates tags for `taggd2`, when `taggd1` stays clean, without tags.

**Comment by rafalolszewskii** [comment]
Nevermind, I've found information in past issue (using BS tabs)

**Comment by timseverien** [comment]
I looked into it, and it's not really a bug. Nor do I have the ambition to "fix" the inner workings of browsers. Long story short: the browser won't allow you to have one element at several places in the DOM tree.

In a nutshell, this is what's happening:

1. You initialise a tag. This tag contains the elements (button and popup) that are put over the image.
2. That tag is put in an array, `tags`.
3. You pass the tags to your first instance, `taggd1`, which puts them over `tagImage1`.
4. You pass the tags to your second instance, `taggd2`, which puts them over `tagImage2`.
5. The browser panics, because you can't have one element at two places, and removes the element from `tagImage1` in order to place it over `tagImage2`.

The solution below isn't pretty, but should work:

```js
// Original tags
const tags1 = [ ... ];
// Create a new array of copies
const tags2 = tag1.map(tag => Taggd.Tag.createFromObject(tag.toJSON()));

const tagg1 = new Taggd(tagImage1, options, tags1);
const tagg2 = new Taggd(tagImage2, options, tags2);
```

Ideally, you want to initialise `tags1` and `tags2` separately:

```js
// List of Taggd.Tag.createFromObject()-compliant objects
const tags = [
  { ... },
  { ... },
  { ... },
];

const tags1 = tags.map(tag => Taggd.Tag.createFromObject(tag));
const tags2 = tags.map(tag => Taggd.Tag.createFromObject(tag));
```

Please let me know if that works for you.
