### ISSUE TITLE
V3 Version - How to get Pixels

### ISSUE THREAD

**Issue by dulisha** [timseverien/taggd#59]
I was looking forward to use pixels, instead (0-1)
How i can do this?

I use original code for V3 version that getting tags using
taggd.getTags();

**Comment by timseverien** [comment]
Due to it’s responsiveness, you can’t do that anymore. In previous versions, I calculated the CSS percentages based on the image’s size. This was relatively error-prone and required the Taggd to wait for the image to finish loading, increasing time before the component would be interactive.

If you are dying to store the coordinates in pixels, you will have to map the coordinates to pixels yourself using `normalizedCoordinate * imageSize`, where `normalizedCoordinate` is the 0-1 coordinate:

```js
const tag = taggd.getTag(0);
const coordinatePixels = {
  x: tag.position.x * taggd.image.originalWidth,
  y: tag.position.y * taggd.image.originalHeight,
};
```

The same goes the other way around using `pixelCoordinate / imageSize`:

```
const tag = new Taggd.Tag.createFromObject({
  text: 'Hello World!',
  position: {
    x: 1337 / image.originalWidth,
    y: 1337 / image.originalHeight,
  },
});
```

**Comment by dulisha** [comment]
Already figure out.
If it helps, i have used original image width and height, and based on the 0 to 1% calculated the PX size.

Function: key: 'toJSON', 1911 aprox line.
<pre>
// added
var realWidthPx = $('.taggd > img').prop('naturalWidth');
var realHeightPx = $('.taggd > img').prop('naturalHeight');

// replaced
position: {
          x: parseFloat(this.wrapperElement.style.left)*(realWidthPx/100),
          y: parseFloat(this.wrapperElement.style.top)*(realHeightPx/100)
},
</pre>

**Comment by dulisha** [comment]
I still use 0 to 1% when displaying tags. But, because of using canvas, i need it to add several notes once when user click on tags, and then save it using imgBase64. The same image i was sending to another Service, which this tool become amazing for what i was trying to build.
