### ISSUE TITLE
I'm wondering. Is it possible to add a web site in a tag and navigate the web site when clicking?

### ISSUE THREAD

**Issue by hongsh1126** [timseverien/taggd#68]
I'm wondering. Is it possible to add a web site in a tag and navigate the web site when clicking?
Please let me know about it.
Thank you,

Sam

**Comment by timseverien** [comment]
Yep. You can do that by using HTML for the tag's text:

```
{
  text: '<a href="#">foo</a>'
}
```

**Comment by hongsh1126** [comment]
Thank you for reply, but it's not a html tag. I'd like to know how to make a program which can allow to add a website on an image. I'd like to see the program code for like facebook tag. Thank you!

**Comment by timseverien** [comment]
I don't think I understand. Are you trying to place tags on top of a website?

**Comment by hongsh1126** [comment]
I mean I'd like to make a program code that can add a website on an image file. I'm not making a html code. I mean actual executive program file. Thank you!

**Comment by timseverien** [comment]
Right. If you're trying to build a desktop application or mobile app, you will need some kind of WebView to display things with Taggd because Taggd is built for the web.

I would love to give you better or more advice, but I'm afraid we have reached the limit of my expertise and I can't trust myself to give _good_ advice.
